version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neurona_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Server/NeuronaTask.Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=neurona_db;Username=admin;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

#  frontend:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    environment:
#      - NEXT_PUBLIC_GRAPHQL_URI=http://backend:8080/graphql
#    depends_on:
#      - backend

volumes:
  postgres_data: